"""Initial migration

Revision ID: f09ce062272c
Revises: 0253211db6b4
Create Date: 2024-07-21 21:19:14.870173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09ce062272c'
down_revision = '0253211db6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
